version: '3'
services:
  web:
    build: .
    ports:
    - "3005:3005"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
